// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/codigician/remote-code-execution/internal/handler (interfaces: RemoteCodeExecutorService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	codexec "github.com/codigician/remote-code-execution/internal/codexec"
	gomock "github.com/golang/mock/gomock"
)

// MockRemoteCodeExecutorService is a mock of RemoteCodeExecutorService interface.
type MockRemoteCodeExecutorService struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteCodeExecutorServiceMockRecorder
}

// MockRemoteCodeExecutorServiceMockRecorder is the mock recorder for MockRemoteCodeExecutorService.
type MockRemoteCodeExecutorServiceMockRecorder struct {
	mock *MockRemoteCodeExecutorService
}

// NewMockRemoteCodeExecutorService creates a new mock instance.
func NewMockRemoteCodeExecutorService(ctrl *gomock.Controller) *MockRemoteCodeExecutorService {
	mock := &MockRemoteCodeExecutorService{ctrl: ctrl}
	mock.recorder = &MockRemoteCodeExecutorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteCodeExecutorService) EXPECT() *MockRemoteCodeExecutorServiceMockRecorder {
	return m.recorder
}

// ExecOnce mocks base method.
func (m *MockRemoteCodeExecutorService) ExecOnce(arg0 context.Context, arg1 codexec.ExecutionInfo) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecOnce", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecOnce indicates an expected call of ExecOnce.
func (mr *MockRemoteCodeExecutorServiceMockRecorder) ExecOnce(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecOnce", reflect.TypeOf((*MockRemoteCodeExecutorService)(nil).ExecOnce), arg0, arg1)
}
