// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/grpc/rce.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodeExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang    string `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Args    string `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *CodeExecutionRequest) Reset() {
	*x = CodeExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_rce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeExecutionRequest) ProtoMessage() {}

func (x *CodeExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeExecutionRequest.ProtoReflect.Descriptor instead.
func (*CodeExecutionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rce_proto_rawDescGZIP(), []int{0}
}

func (x *CodeExecutionRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CodeExecutionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CodeExecutionRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type CodeExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output          string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExecutionTimeMs int64  `protobuf:"varint,2,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
}

func (x *CodeExecutionResponse) Reset() {
	*x = CodeExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_rce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeExecutionResponse) ProtoMessage() {}

func (x *CodeExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_rce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeExecutionResponse.ProtoReflect.Descriptor instead.
func (*CodeExecutionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_rce_proto_rawDescGZIP(), []int{1}
}

func (x *CodeExecutionResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CodeExecutionResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

var File_internal_grpc_rce_proto protoreflect.FileDescriptor

var file_internal_grpc_rce_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x58, 0x0a, 0x14, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x5b, 0x0a, 0x15, 0x43, 0x6f, 0x64,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x32, 0x58, 0x0a, 0x13, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6f, 0x64, 0x69, 0x67, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x2d, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_rce_proto_rawDescOnce sync.Once
	file_internal_grpc_rce_proto_rawDescData = file_internal_grpc_rce_proto_rawDesc
)

func file_internal_grpc_rce_proto_rawDescGZIP() []byte {
	file_internal_grpc_rce_proto_rawDescOnce.Do(func() {
		file_internal_grpc_rce_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_rce_proto_rawDescData)
	})
	return file_internal_grpc_rce_proto_rawDescData
}

var file_internal_grpc_rce_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_rce_proto_goTypes = []interface{}{
	(*CodeExecutionRequest)(nil),  // 0: grpc.CodeExecutionRequest
	(*CodeExecutionResponse)(nil), // 1: grpc.CodeExecutionResponse
}
var file_internal_grpc_rce_proto_depIdxs = []int32{
	0, // 0: grpc.codeExecutorService.Exec:input_type -> grpc.CodeExecutionRequest
	1, // 1: grpc.codeExecutorService.Exec:output_type -> grpc.CodeExecutionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_rce_proto_init() }
func file_internal_grpc_rce_proto_init() {
	if File_internal_grpc_rce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_rce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_rce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_rce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_rce_proto_goTypes,
		DependencyIndexes: file_internal_grpc_rce_proto_depIdxs,
		MessageInfos:      file_internal_grpc_rce_proto_msgTypes,
	}.Build()
	File_internal_grpc_rce_proto = out.File
	file_internal_grpc_rce_proto_rawDesc = nil
	file_internal_grpc_rce_proto_goTypes = nil
	file_internal_grpc_rce_proto_depIdxs = nil
}
