attachStdin: true
attachStdout: true
attachStderr: true
tty: true
cmd:
  - "bash"
image: "codigician/all-in-one-ubuntu:v1-amd64"

# container host config
mounts:
  - type: "bind"
    source: "/target"
    target: "/target"